version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin.01234
      MYSQL_DATABASE: patientdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  mongo:
    image: mongo:5.0
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  patient-service:
    build:
      context: ./patient-service
    container_name: patient-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/patientdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin.01234
    networks:
      - backend

  note-service:
    build:
      context: ./note-service
    container_name: note-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: notesdb
    networks:
      - backend

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - patient-service
      - auth-service
    environment:                   
      JWT_SECRET: p9_6Y7QpA2mZb4RkC7tU1nV9xJ3sL8wE5hT2yG6qM1rD4fP8uK0cN5bV2zX7aL1
    networks:
      - backend

  patient-ui-service:
    build:
      context: ./patient-ui-service
    container_name: patient-ui-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/patientdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin.01234
    networks:
      - backend

  risk-assessment-service:
    build:
      context: ./risk-assessment-service
    container_name: risk-assessment-service
    ports:
      - "8084:8084"
    depends_on:
      - patient-service
      - note-service
    networks:
      - backend

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8085:8085"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/patientdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin.01234
      JWT_SECRET: p9_6Y7QpA2mZb4RkC7tU1nV9xJ3sL8wE5hT2yG6qM1rD4fP8uK0cN5bV2zX7aL1
 
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
  mongo-data:
