server:
  port: ${SERVER_PORT:8083}
spring:
  application:
    name: risk-assessment-service
patient:
  api:
    base-url: ${PATIENT_API_BASE_URL}
note:
  api:
    base-url: ${NOTE_API_BASE_URL}
management:
  endpoints:
    web:
      exposure:
        include: health,info
