spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: auth-service
          uri: http://auth-service:8085
          predicates:
            - Path=/auth/**

        - id: patient-service
          uri: http://patient-service:8081
          predicates:
            - Path=/patients/**

        - id: note-service
          uri: http://note-service:8082
          predicates:
            - Path=/notes/**

        - id: risk-assessment-service
          uri: http://risk-assessment-service:8083
          predicates:
            - Path=/risk/**

        - id: access-denied-page
          uri: http://patient-ui-service:8084
          predicates:
            - Path=/access-denied

        - id: patient-ui-service
          uri: http://patient-ui-service:8084
          predicates:
            - Path=/ui/**
          filters:
            - StripPrefix=1
