server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters: [ PreserveHostHeader ]
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: auth-service
          uri: http://auth-service:8085
          predicates: [ Path=/auth/** ]

        - id: patient-ui
          uri: http://patient-ui-service:8084
          predicates: [ Path=/ui/** ]
          filters: [ StripPrefix=1 ]

        - id: patient-service
          uri: http://patient-service:8081
          predicates: [ Path=/patients/** ]
          filters: [ StripPrefix=1 ]

        - id: note-service
          uri: http://note-service:8082
          predicates: [ Path=/notes/** ]
          filters: [ StripPrefix=1 ]

        - id: risk-assessment-service
          uri: http://risk-assessment-service:8083
          predicates: [ Path=/risk/** ]
          filters: [ StripPrefix=1 ]

management:
  endpoints:
    web:
      exposure:
        include: health,info
