server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
        - RewriteLocationResponseHeader=AS_IN_REQUEST, Location
        - RemoveResponseHeader=Server
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin RETAIN_FIRST

      routes:
        # =======================
        # FRONT / UI
        # =======================
        - id: patient-ui
          uri: http://localhost:8084
          predicates:
            - Path=/ui/**
          filters: []   # ne pas enlever /ui

        - id: ui-root
          uri: http://localhost:8084
          predicates:
            - Path=/
          filters:
            - SetPath=/

        # =======================
        # AUTH
        # =======================
        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader=Authorization
            - StripPrefix=0

        - id: login-to-auth
          uri: http://localhost:8085
          predicates:
            - Path=/login
          filters:
            - SetPath=/auth/login
            - RemoveRequestHeader=Authorization

        # NEW: /logout (compat) -> /auth/logout
        - id: logout-to-auth
          uri: http://localhost:8085
          predicates:
            - Path=/logout
          filters:
            - SetPath=/auth/logout
            - RemoveRequestHeader=Authorization

        # =======================
        # APIs (Option B : validation dans chaque MS)
        # =======================
        - id: patient-api
          uri: http://localhost:8081
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=0

        - id: note-api
          uri: http://localhost:8082
          predicates:
            - Path=/api/notes/**
          filters:
            - StripPrefix=0

        - id: risk-api
          uri: http://localhost:8083
          predicates:
            - Path=/api/risk/**
          filters:
            - StripPrefix=0

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:8080
              - http://localhost:8084
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: DEBUG
    reactor.netty.http.client: WARN

jwt:
  secret: ${JWT_SECRET:0123456789abcdefghijklmnopqrstuvwxyz012345}
