server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: patient-service
          uri: http://patient-service:8081
          predicates:
            - Path=/patients/**

        - id: note-service
          uri: http://note-service:8083
          predicates:
            - Path=/notes/**

        - id: risk-assessment-service
          uri: http://risk-assessment-service:8084
          predicates:
          - Path=/assess/**
