spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/notesdb}

server:
  port: ${SERVER_PORT:8082}

jwt:
  # Secret partagé avec auth-service, gateway, patient-service, risk-assessment-service, patient-ui-service
  secret: ${JWT_SECRET:0123456789abcdefghijklmnopqrstuvwxyz012345}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: INFO
    com.medilabo.noteservice: INFO
