package com.medilabo.riskassessment.dto;

import java.time.Instant;

/**
 * Application: com.medilabo.riskassessment.dto
 *
 * Represents a medical note transferred from the note-service to
 * the risk-assessment-service.
 * <p>
 * Used to analyze medical content for diabetes risk evaluation.
 * </p>
 */
public class NoteDTO {

    /** Unique note identifier (generated by MongoDB in note-service). */
    private Long id;

    /** Identifier of the patient associated with this note. */
    private Long patientId;

    /** Textual content of the medical note. */
    private String content;

    /** Timestamp when the note was created. */
    private Instant createdAt;

    /** Timestamp when the note was last updated. */
    private Instant updatedAt;

    /** Default constructor (required for JSON deserialization). */
    public NoteDTO() {}

    /** Full constructor. */
    public NoteDTO(Long id, Long patientId, String content, Instant createdAt, Instant updatedAt) {
        this.id = id;
        this.patientId = patientId;
        this.content = content;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /** Simplified constructor (only for content-based notes). */
    public NoteDTO(String content) {
        this.content = content;
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public Long getPatientId() { return patientId; }
    public void setPatientId(Long patientId) { this.patientId = patientId; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }

    public Instant getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(Instant updatedAt) { this.updatedAt = updatedAt; }
}
