server.port=8085
spring.thymeleaf.cache=false
server.forward-headers-strategy=framework

# même secret que le gateway & autres services
JWT_SECRET=0123456789abcdefghijklmnopqrstuvwxyz012345
JWT_TTL_SECONDS=43200

# base URL du gateway (pour redirections absolues)
ui.base-url=http://localhost:8080

# cookie (doit matcher le Gateway)
security.jwt.cookie.name=JWT_TOKEN
security.jwt.cookie.secure=false
security.jwt.cookie.samesite=Lax
security.jwt.ttl-seconds=43200
