server:
  port: 8084

spring:
  application:
    name: patient-ui-service
  thymeleaf:
    cache: true

# Secret identique à auth-service & gateway (passe-le via env dans compose)
JWT_SECRET: ${JWT_SECRET}

# En Docker, on vise le nom du service gateway
gateway:
  base-url: http://gateway-service:8080

# Chemins DERRIÈRE la gateway (avec /api)
patients:
  api:
    base: /api/patients
notes:
  api:
    base: /api/notes
risk:
  api:
    base: /api/risk

management:
  endpoints:
    web:
      exposure:
        include: health,info
